version: '3'

services:

  php:
    container_name: semihkislarchallenge-php
    build:
      context: ./docker/php
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - cache
    environment:
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
      REDIS_PORT: 6379
      REDIS_HOST: cache
    networks:
      - semihkislarchallenge-app-network
    working_dir: /srv/www

  nginx:
    container_name: semihkislarchallenge-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8800:80
    volumes:
      - ./:/srv/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - semihkislarchallenge-app-network

  mysql:
    container_name: semihkislarchallenge-mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 33306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 123456
    networks:
      - semihkislarchallenge-app-network

  cache:
    image: redis:4.0.6
    ports:
      - '16379:6379'
    networks:
      - semihkislarchallenge-app-network
      
#Docker Networks
networks:
  semihkislarchallenge-app-network:
    driver: bridge
